name: Get a Kanye Quote

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/15 * * * *' # Runs every 15 minutes

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  kanye-quote:
    # Name the Job
    name: Get a Kanye Quote
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add Fetched Quote to README
        run: |
          echo '"' $(curl -s https://api.kanye.rest/ |  python -c "import sys,json; print json.load(sys.stdin)['quote']") '" - Kanye West\n\nLast Updated: ' $(date -u)>> quote.txt
          cat readme-template.md quote.txt > README.md
      - name: Commit and push
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git status
          git add README.md
          timestamp=$(date -u)
          git commit -m "Latest update: ${timestamp}" || exit 0
          git push
